### PR TITLE
Feature/custom logs

### PR DESCRIPTION
**Pull request by gathecageorge**
Add promtail to push logs to central server

### CODE REVIEW

**Comment by yorickdowne** [comment]
This really can be in prometheus.yml I think. I'm not sure we need a separate file for it.

**Comment by gathecageorge** [comment]
Sure can merge them, means will never need metrics only without logs which is our case.

**Comment by yorickdowne** [comment]
Thanks! What do the pipeline stages all do? From memory we don’t have that in Eth Docker - depending on what these do, we may want to

**Comment by gathecageorge** [comment]
We do have them https://github.com/eth-educators/eth-docker/blob/main/promtail/global.yml those are part of configuring promtail on how to label logs from containers. Getting attributes assigned to containers [tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'] and processing them as labels. When docker is running containers logs are usually in /var/lib/docker/containers as text files, so promtail reads them and attaches tags as labels

**Pull request merged**
